/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IWorkerService,
} from './utils/utils';

export namespace Components {
  interface MableSpinner {}
  interface PasswordReset {}
  interface StockFinder {}
  interface StockPrice {
    'stockSymbol': string;
  }
  interface WorkerService {
    'service': IWorkerService;
  }
  interface WorkerServices {
    'services': IWorkerService[];
  }
}

declare global {


  interface HTMLMableSpinnerElement extends Components.MableSpinner, HTMLStencilElement {}
  const HTMLMableSpinnerElement: {
    prototype: HTMLMableSpinnerElement;
    new (): HTMLMableSpinnerElement;
  };

  interface HTMLPasswordResetElement extends Components.PasswordReset, HTMLStencilElement {}
  const HTMLPasswordResetElement: {
    prototype: HTMLPasswordResetElement;
    new (): HTMLPasswordResetElement;
  };

  interface HTMLStockFinderElement extends Components.StockFinder, HTMLStencilElement {}
  const HTMLStockFinderElement: {
    prototype: HTMLStockFinderElement;
    new (): HTMLStockFinderElement;
  };

  interface HTMLStockPriceElement extends Components.StockPrice, HTMLStencilElement {}
  const HTMLStockPriceElement: {
    prototype: HTMLStockPriceElement;
    new (): HTMLStockPriceElement;
  };

  interface HTMLWorkerServiceElement extends Components.WorkerService, HTMLStencilElement {}
  const HTMLWorkerServiceElement: {
    prototype: HTMLWorkerServiceElement;
    new (): HTMLWorkerServiceElement;
  };

  interface HTMLWorkerServicesElement extends Components.WorkerServices, HTMLStencilElement {}
  const HTMLWorkerServicesElement: {
    prototype: HTMLWorkerServicesElement;
    new (): HTMLWorkerServicesElement;
  };
  interface HTMLElementTagNameMap {
    'mable-spinner': HTMLMableSpinnerElement;
    'password-reset': HTMLPasswordResetElement;
    'stock-finder': HTMLStockFinderElement;
    'stock-price': HTMLStockPriceElement;
    'worker-service': HTMLWorkerServiceElement;
    'worker-services': HTMLWorkerServicesElement;
  }
}

declare namespace LocalJSX {
  interface MableSpinner {}
  interface PasswordReset {}
  interface StockFinder {
    'onMableSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface StockPrice {
    'stockSymbol'?: string;
  }
  interface WorkerService {
    'service'?: IWorkerService;
  }
  interface WorkerServices {
    'services'?: IWorkerService[];
  }

  interface IntrinsicElements {
    'mable-spinner': MableSpinner;
    'password-reset': PasswordReset;
    'stock-finder': StockFinder;
    'stock-price': StockPrice;
    'worker-service': WorkerService;
    'worker-services': WorkerServices;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mable-spinner': LocalJSX.MableSpinner & JSXBase.HTMLAttributes<HTMLMableSpinnerElement>;
      'password-reset': LocalJSX.PasswordReset & JSXBase.HTMLAttributes<HTMLPasswordResetElement>;
      'stock-finder': LocalJSX.StockFinder & JSXBase.HTMLAttributes<HTMLStockFinderElement>;
      'stock-price': LocalJSX.StockPrice & JSXBase.HTMLAttributes<HTMLStockPriceElement>;
      'worker-service': LocalJSX.WorkerService & JSXBase.HTMLAttributes<HTMLWorkerServiceElement>;
      'worker-services': LocalJSX.WorkerServices & JSXBase.HTMLAttributes<HTMLWorkerServicesElement>;
    }
  }
}


